<?php

/**
 * @file
 * Contains mz_crud.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
* Implements hook_help().
 */
function mz_crud_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the mz_crud module.
        case 'help.page.mz_crud':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('CRUD entity api') . '</p>';
            return $output;

        default:
    }
}
