<?php

/**
 * @file
 * Contains html_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_help().
 */
function html_page_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the html_page module.
        case 'help.page.html_page':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Build HTML Page') . '</p>';
            return $output;
        default:
    }
}



function html_page_preprocess_html(&$variables)
{

    $node = \Drupal::request()->attributes->get('node');
    if ($node && $node->bundle()=='html_page') {
        $body = $node->body->value;
     //   $var =  Json::decode($node->field_json->value);
        $var['entity'] = $node ;
        $variables['html_page'] = [
            '#type' => 'inline_template',
            '#template' => $body,
            '#context' => $var
        ];
      
    }

    // echo "hello go"; die();
    // if (isset($variables['node']) && $variables['node']->getType() == 'html_page') {
    //   $view_mode = $variables['view_mode'];
    //   if($view_mode=='full') {
    //     $node = ($variables['node']);
    //     $body = $node->body->value ;
    //     $variables['html_page'] = [
    //       '#type' => 'inline_template',
    //       '#template' => $body
    //     ];
    //    // $variables['html_page'] = \Drupal::service('renderer')->render($body);
    //   }
    // }
}
