<?php

/**
 * @file
 * Contains html_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_help().
 */
function commande_management_management_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the html_page module.
        case 'help.page.commande_management':
            $output = '';
            $output .= '<h3>' . t('commande_management') . '</h3>';
            $output .= '<p>' . t('commande_management system') . '</p>';
            return $output;
        default:
    }
}

