<?php

/**
 * @file
 * Contains drupal_helper.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_helper_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the drupal_helper module.
        case 'help.page.drupal_helper':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Usual Functions for beginner developper').'</p>';
            $output .= '<p>' . t('For more information, visit the <a href=":url">Drupal Helper project page</a>.', [':url' => 'https://www.drupal.org/project/drupal_helper']).'</p>';

      return $output;

        default:
    }
}
/**
 * Implements hook__suggestions_HOOK_alter().
 */
function drupal_helper_theme_suggestions_group_alter(array &$suggestions, array $variables) {
    if(isset($variables['elements']['#group']) && is_object($variables['elements']['#group']->view)){
        $view_name = ($variables['elements']['#group']->view->id());
        $display_view = ($variables['elements']['#group']->view->getDisplay());
        $suggestions[] = 'group__view__' . $view_name;
        foreach ($display_view as $key => $display){
            if($key=='display'){
                $suggestions[] = 'group__view__' . $view_name.'__'.$display['id'];
            }
        }

    }
    return $suggestions;
}
/**
 * Implements hook__suggestions_HOOK_alter().
 */
function drupal_helper_theme_suggestions_node_alter(array &$suggestions, array $variables) {
    if(isset($variables['elements']['#node']) && is_object($variables['elements']['#node']->view)){
        $view_name = ($variables['elements']['#node']->view->id());
        $display_view = ($variables['elements']['#node']->view->getDisplay());
        $suggestions[] = 'node__view__' . $view_name;
        foreach ($display_view as $key => $display){
            if($key=='display'){
                $suggestions[] = 'node__view__' . $view_name.'__'.$display['id'];
            }
        }

    }
    return $suggestions;
}
/**
 * Implements hook__suggestions_HOOK_alter().
 */
function drupal_helper_theme_suggestions_block_alter(array &$suggestions, array $variables) {
    // Add theme suggestions to blocks based on region.
    if(isset($variables['elements']['content']['#block_content'])) {
        $block_object = $variables['elements']['content']['#block_content'];
        if(is_object($block_object) && $block_object->info->getValue()){
            $val = $block_object->info->getValue();
            if(isset($val[0])){
                $title = strtolower($block_object->info->getValue()[0]['value']);
                $suggestions[] = 'block__' . $title;
            }

        }
    }
    return $suggestions;
}
/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
// function drupal_helper_preprocess_html(&$variables) {
//     $query = Drupal::request()->query->all();
//     if(isset($query['lang']) && $query['lang']){
//         $languageManager = \Drupal::languageManager();
//         $customLanguageNegotiator = \Drupal::service('drupal_helper.language_negotiator');
//         $languageManager->setNegotiator($customLanguageNegotiator);   
//         $languageManager->reset(); 
//         $languageManager->getNegotiator()->setLanguageCode($query['lang']);  
//     }
//     $variables['#attached']['library'][] = "drupal_helper/drupal_helper";
// }
/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
function drupal_helper_preprocess_html(&$variables) {
  $config = \Drupal::config('drupal_helper.features');
  $is_redirect_to_login_if_not_connect = $config->get('redirect_to_login_if_not_connect');
  $route_match = \Drupal::service('current_route_match');

  if($is_redirect_to_login_if_not_connect == 1){
    $service = \Drupal::service('drupal.helper');
    $current_user = \Drupal::currentUser();
    if ($current_user->isAnonymous()) {
        $route_name = $route_match->getRouteName();
        if(  $route_name != 'user.login' ){
            $service->helper->redirectTo('/user/login');
        }
    }
}
  

}
  /**
 * Implements hook_theme_suggestions_HOOK_alter() for page templates.
 */
function drupal_helper_theme_suggestions_page_alter(array &$suggestions, array $variables) {
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
      // Check if the current page is a node page.
      if ($node instanceof \Drupal\node\NodeInterface) {
        // Get the content type of the node.
        $node_type = $node->getType();
        // Add a suggestion based on the content type.
        $suggestions[] = 'page__node_' . $node_type;
        $alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $node->id());
        if( $alias){
          $suggestions[] = 'page__node_'.$node_type.'_'. str_replace('/', '_', $alias);
        }
      }
    }
  }
